### PR TITLE
Add new compromise reaction class

### PR DESCRIPTION
**Pull request by AustinT**
This PR adds a new compromise Reaction class in a new file: `syntheseus/interface/reaction.py`. The class has the features we discussed in #58 [^1]. The class also includes a basic test.

The new classes is not used anywhere at the moment[^2]. I will refactor the rest of the code to use it in another PR. I thought it would be test to propose the class in isolation first to avoid doing all the refactoring, then re-doing it if we decide to make additional changes.

[^1]: Except for the `unique_reactants` alias. After thinking about it a bit more, if users know to use `unique_reactants` then they could just as easily write `set(reactants)`.

[^2]: Except that I moved the `REACTION_SEPARATOR` constant to `reaction.py` and changed resulting imports. It seemed odd to have it in `molecule.py`

### CODE REVIEW

**Review by kmaziarz — APPROVED** [review]
> If users know to use `unique_reactants` then they could just as easily write `set(reactants)`.

This may be true, but I think another advantage of having `unique_reactants` is that it makes it more clear the `reactants` are _not_ unique. Otherwise I could imagine someone knowing they need unique reactants, but not realizing `reactants` are not already unique... Apart from that LGTM.

**Comment by AustinT** [comment]
> > If users know to use `unique_reactants` then they could just as easily write `set(reactants)`.
> 
> This may be true, but I think another advantage of having `unique_reactants` is that it makes it more clear the `reactants` are _not_ unique. Otherwise I could imagine someone knowing they need unique reactants, but not realizing `reactants` are not already unique... Apart from that LGTM.

Good point. I added them to the base class. Do you think that is the appropriate place to add them @kmaziarz? There is some redundancy between the implementation in `MultiProductReaction` and `SingleProductReaction` but it is very small.

**Review by mrwnmsr — APPROVED** [review]

**Comment by kmaziarz** [comment]
> I added them to the base class. Do you think that is the appropriate place to add them @kmaziarz? There is some redundancy between the implementation in `MultiProductReaction` and `SingleProductReaction` but it is very small.

Yes, what you've done seems reasonable.

**Comment by AustinT** [comment]
> > I added them to the base class. Do you think that is the appropriate place to add them @kmaziarz? There is some redundancy between the implementation in `MultiProductReaction` and `SingleProductReaction` but it is very small.
> 
> Yes, what you've done seems reasonable.

Sounds good, I'll merge this then.

**Pull request merged**
